os: osx
osx_image: xcode8
language: objective-c
sudo: false
notifications:
  email: false
before_install:
- npm install -g cordova@
before_script:
- cordova create tmp
- rm tmp/package.json
- mv tmp/* .
- rm -Rf tmp
- cordova platform add ios
script:
- npm run-script test

